# Generated by Django 3.2.16 on 2023-01-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230110_2126'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='could_not_follow_itself',
        ),
    ]
